### PR TITLE
add a Stop() method to the SSH server

### PR DESCRIPTION
**Pull request by petergardfjall**
It would be useful to allow a running SSH server to be stopped (and perhaps restarted), for example to be used within tests.

### CODE REVIEW

**Comment by sosedoff** [comment]
Sorry i've been out for a while. I'll take a look, maybe i can just merge it as-is.

**Comment by petergardfjall** [comment]
@sosedoff don't want to be pushy, but do you feel okay with including this?

**Comment by larsla** [comment]
+1
This PR solves the issue I had.

**Comment by sosedoff** [comment]
here you go, i'll revisit this for http server when i have time. sorry, been very busy with client work

**Comment by petergardfjall** [comment]
Thanks!

**Pull request merged**
